api_platform:
    title: Hello API Platform
    version: 1.0.0

    show_webby: false


    # Mercure integration, remove if unwanted
    mercure: ~
    formats:
        jsonld: ['application/ld+json']
        html: ['text/html']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        extra_properties:
            standard_put: true

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

    resource_class_directories:
        - '%kernel.project_dir%/src/ValueObject'
